# Generated by Django 2.1.2 on 2018-10-21 09:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('capstone', '0002_auto_20181021_1457'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Goals',
            new_name='Goal',
        ),
        migrations.RenameModel(
            old_name='Milestones',
            new_name='Milestone',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
