# Generated by Django 2.1.2 on 2018-10-21 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0003_auto_20181021_1502'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='link',
            new_name='milestone',
        ),
    ]
