# Generated by Django 2.1.2 on 2018-10-21 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0004_auto_20181021_1507'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='members',
            new_name='member',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='group_name',
            new_name='name',
        ),
    ]
