# Generated by Django 2.1.2 on 2018-10-21 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0005_auto_20181022_0034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='name',
            new_name='group_name',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='member',
            new_name='members',
        ),
    ]
