# Generated by Django 2.1.2 on 2018-10-22 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0008_group_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='title',
            field=models.CharField(max_length=140),
        ),
    ]
