# Generated by Django 2.1.2 on 2018-10-23 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0009_auto_20181023_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='description',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='content',
            field=models.TextField(max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='update',
            name='text',
            field=models.TextField(max_length=350),
        ),
    ]
