# Generated by Django 2.1.2 on 2018-10-23 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0013_auto_20181023_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_name',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
