# Generated by Django 2.1.2 on 2018-10-24 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0014_auto_20181023_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='invites',
        ),
    ]
