# Generated by Django 2.1.2 on 2018-10-25 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0015_remove_group_invites'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
